# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: QNX Build (gated)

on:
  workflow_call:
    inputs:
      bazel-target:
        description: Bazel target to build with the QNX toolchain
        required: false
        default: //...
        type: string
      bazel-config:
        description: Bazel configuration to use for QNX builds
        required: false
        default: x86_64-qnx
        type: string
      credential-helper:
        description: Relative or absolute path to the QNX credential helper script
        required: false
        default: .github/tools/qnx_credential_helper.py
        type: string
      environment-name:
        description: Environment gating access to QNX secrets
        required: false
        default: workflow-approval
        type: string
      bazel-disk-cache:
        description: Enable Bazel disk cache on GitHub. The value can be a string to use as cache key for separating workflows
        required: false
        default: 'true'
        type: string
      extra-bazel-flags:
        description: Additional Bazel flags to pass to the build command (whitespace separated)
        required: false
        default: ''
        type: string
      bazel-test-target:
        description: Bazel test targets to run with the QNX toolchain (leave empty to skip tests)
        required: false
        default: ''
        type: string
      extra-bazel-test-flags:
        description: Additional Bazel flags to pass to the test command (whitespace separated)
        required: false
        default: ''
        type: string
      score-qnx-license-server:
        description: Address of the QNX license server (e.g. '6287@license-server-hostname'). Configures user.bazelrc with related action env vars.
        required: false
        type: string
    secrets:
      score-qnx-license:
        description: Base64-encoded QNX license content
        required: true
      score-qnx-user:
        description: QNX account username
        required: true
      score-qnx-password:
        description: QNX account password
        required: true

jobs:
  approval:
    # Require approvals for PRs from forks, but not for same-repository PRs, merge queues or push events.
    # If the job is already in the merge queue, the changes have already been reviewed and approved.
    # Thus the approval is already implicit by the review approval.
    if: github.event_name == 'pull_request_target' && (github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name)
    environment: ${{ inputs.environment-name }}
    runs-on: ${{ vars.runner_labels_ghub_standard_x64 && fromJSON(vars.runner_labels_ghub_standard_x64) || vars.REPO_RUNNER_LABELS && fromJSON(vars.REPO_RUNNER_LABELS) || 'ubuntu-latest' }}
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Blocking on approval
        run: 'true'

  qnx-build:
    name: Build QNX target
    # run this job always unless the workflow was canceled; approval may still be skipped by intention
    # Do not use always(), see https://docs.github.com/en/actions/reference/workflows-and-actions/expressions#always
    if: ${{ !cancelled() }}
    needs: approval
    runs-on: ${{ vars.runner_labels_ghub_standard_x64 && fromJSON(vars.runner_labels_ghub_standard_x64) || vars.REPO_RUNNER_LABELS && fromJSON(vars.REPO_RUNNER_LABELS) || 'ubuntu-latest' }}
    permissions:
      contents: read
      pull-requests: read

    steps:
      - uses: eclipse-score/more-disk-space@6a3b48901846bf7f8cc985925157d71a8973e61f # v1
        with:
          level: 4

      - name: Checkout repository (Handle all events)
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          ref: ${{ github.head_ref || github.event.pull_request.head.ref || github.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: Setup Bazel with shared caching
        uses: eclipse-score/cicd-actions/setup-bazel-cache@659dcbed63f6b7fbde88c7850125ea0a0a92f939 # setup-bazel-cache/v0.0.0
        with:
          unique-cache-name: ${{ github.job }}

      - uses: eclipse-score/cicd-actions/unblock-user-namespace-for-linux-sandbox@30ed908edcf367bc38ebff5b386a244f9b6417a7 # 2025-06-04

      - name: Setup QNX SDP usage
        uses: eclipse-score/cicd-actions/setup-qnx-sdp@a2b3c36fc7d1b9d03880d19935c7ac9cfffe58c6 # 2026-05-19
        with:
          qnx-license: ${{ secrets.score-qnx-license }}
          qnx-license-server: ${{ inputs.score-qnx-license-server }}
          qnx-user: ${{ secrets.score-qnx-user }}
          qnx-password: ${{ secrets.score-qnx-password }}
          qnx-credential-helper: ${{ inputs.credential-helper }}
          qnx-license-dir: /opt/score_qnx/license

      - name: Build with QNX toolchain
        run: |
          set -euo pipefail

          bazel build --config ${{ inputs.bazel-config }} \
            --credential_helper=*.qnx.com="${QNX_CREDENTIAL_HELPER}" ${{ inputs.extra-bazel-flags }} -- \
            ${{ inputs.bazel-target }}

      - name: Install qemu
        if: inputs.bazel-test-target != ''
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system

      - name: Enable KVM group permissons
        if: inputs.bazel-test-target != ''
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Test with QNX toolchain
        if: inputs.bazel-test-target != ''
        run: |
          set -euo pipefail

          bazel test --config ${{ inputs.bazel-config }} \
            --credential_helper=*.qnx.com="${QNX_CREDENTIAL_HELPER}" ${{ inputs.extra-bazel-test-flags }} -- \
            ${{ inputs.bazel-test-target }}
